### ISSUE TITLE
I was training with your dataset (lmdb) but error? Can you help me?

### ISSUE THREAD

**Issue by PhanTung-06** [FangShancheng/ABINet#78]
[2022-09-04 08:24:27,580 main.py:229 INFO train-abinet] Construct learner.
[2022-09-04 08:24:27,679 main.py:233 INFO train-abinet] Start training.
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
Traceback (most recent call last):
  File "main.py", line 246, in <module>
    main()
  File "main.py", line 235, in main
    lr=config.optimizer_lr)
  File "/usr/local/lib/python3.7/dist-packages/fastai/basic_train.py", line 200, in fit
    fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
  File "/usr/local/lib/python3.7/dist-packages/fastai/basic_train.py", line 99, in fit
    for xb,yb in progress_bar(learn.data.train_dl, parent=pbar):
  File "/usr/local/lib/python3.7/dist-packages/fastprogress/fastprogress.py", line 39, in __iter__
    if self.total != 0: self.update(0)
  File "/usr/local/lib/python3.7/dist-packages/fastprogress/fastprogress.py", line 59, in update
    self.update_bar(0)
  File "/usr/local/lib/python3.7/dist-packages/fastprogress/fastprogress.py", line 81, in update_bar
    self.on_update(val, f'{pct}[{val}/{tot} {elapsed_t}{self.lt}{remaining_t}{end}]')
  File "/usr/local/lib/python3.7/dist-packages/fastprogress/fastprogress.py", line 134, in on_update
    elif self.parent is not None: self.parent.show()
  File "/usr/local/lib/python3.7/dist-packages/fastprogress/fastprogress.py", line 177, in show
    self.out.update(HTML(self.html_code))
AttributeError: 'NoneType' object has no attribute 'update'

**Comment by kos94ok** [comment]
How was the problem solved?

**Comment by PhanTung-06** [comment]
> How was the problem solved?

Hi, I updated version of python from python3.7 to python3.8. You can try it.
